;;; -*- lexical-binding: t; -*-
(setq native-comp-enable-subr-trampolines nil)
(require 'ert)
(require 'cl-lib)
(load (expand-file-name "../autoload/night-mobile.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t)

(ert-deftest mobile-boundaries-and-lifecycle ()
  (save-window-excursion
    (let ((buffer (generate-new-buffer " mobile-test"))
          (other (generate-new-buffer " mobile-other")))
      (unwind-protect
          (progn
            (switch-to-buffer buffer)
            (delete-other-windows)
            (set-frame-parameter nil 'night/mobile t)
            (setq-local display-line-numbers 'relative)
            (buffer-enable-undo)
            (let ((desktop (selected-window))
                  (mobile (split-window-right)))
              (set-window-buffer mobile buffer)
              ;; Model a mobile frame's window list while retaining a desktop
              ;; window for window-specific property and rendering checks.
              (cl-letf (((symbol-function 'window-list)
                         (lambda (&rest _) (list mobile))))
                (dolist (contents '("" "one" "one\n" "one\ntwo" "one\ntwo\n" "one\n\n"))
                  (erase-buffer)
                  (insert contents)
                  (night/h-mobile-reconcile)
                  (let ((ov (gethash mobile night/h-mobile-overlays)))
                    (when ov
                      (should (< (overlay-end ov) (point-max)))
                      (should (eq (get-char-property (point-min) 'display-line-numbers-disable mobile) t)))
                    (should-not (get-char-property (point-min) 'display-line-numbers-disable desktop))
                    (should (eq display-line-numbers 'relative))))
                (erase-buffer)
                (insert "alpha\nbeta\ngamma\n")
                (night/h-mobile-reconcile)
                (let ((ov (gethash mobile night/h-mobile-overlays)))
                  (goto-char (point-max)) (insert "delta\n")
                  (night/h-mobile-reconcile)
                  (should (eq ov (gethash mobile night/h-mobile-overlays)))
                  (should (< (overlay-end ov) (point-max)))
                  (narrow-to-region 2 8)
                  (night/h-mobile-reconcile)
                  (should (< (overlay-end ov) (point-max)))
                  (should (= (overlay-start ov) (point-min)))
                  (widen)
                  (night/h-mobile-reconcile)
                  (setq buffer-undo-list nil)
                  (undo-boundary)
                  (goto-char (point-min)) (delete-region (point-min) (point-max))
                  (undo-boundary)
                  (night/h-mobile-reconcile)
                  (should-not (overlay-buffer ov))
                  (undo 1)
                  (night/h-mobile-reconcile)
                  (should (gethash mobile night/h-mobile-overlays)))
                (setq-local display-line-numbers t)
                (night/h-mobile-reconcile)
                (should (eq display-line-numbers t))
                (erase-buffer)
                (insert "alpha\nbeta\n")
                (night/h-mobile-reconcile)
                (set-window-buffer mobile other)
                (night/h-mobile-reconcile)
                (should (= 0 (hash-table-count night/h-mobile-overlays)))
                (set-window-buffer mobile buffer)
                (night/h-mobile-reconcile)
                (night/mobile-frame-toggle)
                (should (= 0 (hash-table-count night/h-mobile-overlays)))
                (night/mobile-frame-toggle)
                (should (= 1 (hash-table-count night/h-mobile-overlays)))
                (night/mobile-line-numbers-mode -1)
                (should (= 0 (hash-table-count night/h-mobile-overlays)))))
            (night/mobile-line-numbers-mode 1)
            (night/h-mobile-reconcile)
            (should (= 2 (hash-table-count night/h-mobile-overlays)))
            (delete-other-windows)
            (night/h-mobile-reconcile)
            (should (= 1 (hash-table-count night/h-mobile-overlays)))
            (load (expand-file-name "../autoload/night-mobile.el"
                        (file-name-directory (or load-file-name buffer-file-name))) nil t)
            (should (= 1 (cl-count #'night/h-mobile-reconcile pre-redisplay-functions)))
            (night/mobile-line-numbers-mode -1)
            (should (= 0 (hash-table-count night/h-mobile-overlays))))
        (set-frame-parameter nil 'night/mobile nil)
        (night/mobile-line-numbers-mode -1)
        (kill-buffer buffer)
        (kill-buffer other)))))

(ert-run-tests-batch-and-exit)
