;;; -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'subr-x)
(require 'ert)
(defmacro after! (_features &rest body) `(progn ,@body))
(defmacro add-hook! (&rest _args) nil)
(defmacro z (command &rest args) `(night/test-z ',command ,@args))
(defun night/test-z (&rest _) "inert-emacs-key")
(defmacro comment (&rest _body) nil)
(when (getenv "FIM_PLZ_DIR") (add-to-list 'load-path (getenv "FIM_PLZ_DIR")))
(unless (require 'plz nil t) (provide 'plz))
(load-file (expand-file-name "../autoload/night-llm-fim.el" (file-name-directory (or load-file-name buffer-file-name))))
(defun night/test-fim-wait (proc)
  (let ((deadline (+ (float-time) 10)))
    (while (and (process-live-p proc) (< (float-time) deadline))
      (accept-process-output proc 0.1))
    (accept-process-output nil 0.1)
    (should-not (process-live-p proc))))
(ert-deftest fim-go-stdin-success-and-overrides ()
  (let (result failure finished
        (night/llm-fim-provider 'stub)
        (night/llm-fim-transport 'go))
    (cl-letf (((symbol-function 'night/test-z) (lambda (&rest _) "inert-emacs-key")))
      (let ((proc (night/llm-fim-get "count =" :suffix "tail" :max_tokens 9 :stop '("END")
                    :temperature 0.2
                    :callback (lambda (s) (setq result s))
                    :on-error (lambda (&rest args) (setq failure args))
                    :finally (lambda () (setq finished t)))))
        (should (processp proc))
        (should (equal (cdr (process-command proc)) '("fim")))
        (night/test-fim-wait proc)
        (should-not failure) (should finished) (should (equal result " 0"))))))
(ert-deftest fim-go-http-error ()
  (let (failure finished (night/llm-fim-provider 'broken))
    (cl-letf (((symbol-function 'night/test-z) (lambda (&rest _) "inert-emacs-key")))
      (night/test-fim-wait
       (night/llm-fim-get "inert" :callback #'ignore
         :on-error (lambda (fmt &rest args) (setq failure (apply #'format fmt args)))
         :finally (lambda () (setq finished t))))
      (should finished)
      (should (equal failure "fim-get: broken: HTTP 401 — fabricated failure")))))
(ert-deftest fim-go-cancel-and-slot-claim ()
  (let ((night/llm-fim-provider 'slow) (night/llm-fim-verbose nil) finished)
    (cl-letf (((symbol-function 'night/test-z) (lambda (&rest _) "inert-emacs-key"))
              ((symbol-function 'night/h-llm-fim--ghost-clear) #'ignore))
      (with-temp-buffer
        (let ((proc (night/llm-fim-get "inert" :callback (lambda (_) (ert-fail "inserted cancelled completion"))
                     :on-error #'ignore :finally (lambda () (setq finished t)))))
          (setq night/llm-fim--pending (list :id 5 :process proc))
          (should (night/h-llm-fim--cancel :quiet t))
          (should-not night/llm-fim--pending)
          (should-not (night/h-llm-fim--claim (current-buffer) 5))
          (night/test-fim-wait proc) (should finished)
          (setq night/llm-fim--pending '(:id 6))
          (should (night/h-llm-fim--claim (current-buffer) 6))
          (should-not (night/h-llm-fim--claim (current-buffer) 6)))))))
(ert-deftest fim-provider-picker-and-v1-rollback ()
  (let ((night/llm-fim-transport 'v1) called)
    (night/h-llm-fim--providers-refresh)
    (should (assoc 'codestral night/llm-fim-providers))
    (cl-letf (((symbol-function 'night/llm-fim-get-v1)
               (lambda (&rest args) (setq called args) 'legacy)))
      (should (eq (night/llm-fim-get "inert" :provider 'stub :max_tokens 17 :callback #'ignore) 'legacy))
      (should (equal (car called) "inert"))
      (should (= (plist-get (cdr called) :max_tokens) 17)))))
(ert-deftest fim-v1-real-plz-rollback ()
  (skip-unless (fboundp 'plz))
  (let ((night/llm-fim-transport 'v1) (night/llm-fim-provider 'stub) result failure)
    (cl-letf (((symbol-function 'night/test-z) (lambda (&rest _) "inert-emacs-key")))
      (night/test-fim-wait
       (night/llm-fim-get "legacy =" :callback (lambda (s) (setq result s))
                         :on-error (lambda (&rest args) (setq failure args))))
      (should-not failure) (should (equal result " 0")))))
(ert-run-tests-batch-and-exit)
