;;; -*- lexical-binding: t; -*-
(setq native-comp-enable-subr-trampolines nil)
(require 'ert)
(require 'cl-lib)
(require 'subr-x)

(defvar mobile-clipboard-test-root
  (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))
(load (expand-file-name "autoload/night-mobile-clipboard.el" mobile-clipboard-test-root)
      nil t)

;; Load the actual copy advice without the rest of the interactive Doom setup.
(with-temp-buffer
  (insert-file-contents
   (expand-file-name "autoload/night-clipboard.el" mobile-clipboard-test-root))
  (goto-char (point-min))
  (let (form)
    (while (< (point) (point-max))
      (setq form (read (current-buffer)))
      (when (and (eq (car-safe form) 'defun)
                 (eq (cadr form) 'night/h-kill-skip-whitespace))
        (eval form t)
        (goto-char (point-max))))))

(defvar night/advice-kill-new-unescape-org-enabled-p nil)
(defalias 'equalp #'cl-equalp)

(defmacro mobile-clipboard-test-with-routing (&rest body)
  `(let* ((events nil)
         (kill-ring nil)
         (kill-ring-yank-pointer nil)
         (save-interprogram-paste-before-kill nil)
         (interprogram-cut-function (lambda (_text) (push 'host events)))
         (mobile t))
     (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () mobile))
               ((symbol-function 'night/ssh-p) (lambda () t))
               ((symbol-function 'night/call-process-async)
                (lambda (&rest _args) (push 'legacy events)))
               ((symbol-function 'send-string-to-terminal)
                (lambda (text &optional _terminal) (push text events))))
       (unwind-protect
           (progn
             (advice-add 'kill-new :around #'night/h-kill-skip-whitespace)
             ,@body)
         (advice-remove 'kill-new #'night/h-kill-skip-whitespace)))))

(ert-deftest mobile-clipboard-native-utf8-and-frame-isolation ()
  (mobile-clipboard-test-with-routing
   (let ((text "hello فارسی 🦊\n\n")
         (prior (terminal-parameter nil 'xterm--set-selection)))
     (kill-new text)
     (should (equal events
                    (list (concat "\e]52;c;"
                                  (base64-encode-string
                                   (encode-coding-string text 'utf-8-unix) t)
                                  "\a"))))
     (should (equal (car kill-ring) text))
     (should (eq (terminal-parameter nil 'xterm--set-selection) prior)))
   ;; The same buffer next copied from a desktop frame keeps the host route.
   (setq mobile nil events nil)
   (kill-new "desktop")
   (should (equal events '(legacy host)))))

(ert-deftest mobile-clipboard-limit-and-append ()
  (mobile-clipboard-test-with-routing
   (let ((night/mobile-clipboard-max-bytes 6))
     (kill-new "ééé")
     (should (= (length events) 1))
     (setq events nil)
     (kill-append "x" nil)
     (should (equal (car kill-ring) "éééx"))
     (should-not events))))

(ert-deftest mobile-clipboard-error-restores-terminal ()
  (mobile-clipboard-test-with-routing
   (let ((prior (terminal-parameter nil 'xterm--set-selection)))
     (cl-letf (((symbol-function 'send-string-to-terminal)
                (lambda (&rest _) (error "disconnected terminal"))))
       (kill-new "keep this"))
     (should (equal (car kill-ring) "keep this"))
     (should-not events)
     (should (eq (terminal-parameter nil 'xterm--set-selection) prior)))))

(ert-deftest mobile-clipboard-empty-and-whitespace-policy ()
  (mobile-clipboard-test-with-routing
   (kill-new "   ")
   (should-not events)
   (should-not kill-ring)
   ;; An explicit empty clipboard write can clear it; ordinary whitespace
   ;; kills above retain the existing kill-new policy.
   (night/mobile-clipboard-cut "")
   (should (equal events '("\e]52;c;\a")))))

(defmacro mobile-clipboard-test-with-ssh (&rest body)
  `(let ((night/h-mobile-clipboard-ssh-cache (make-hash-table :test #'equal))
         (night/h-mobile-clipboard-ssh-jobs (make-hash-table :test #'equal))
         (night/mobile-clipboard-max-bytes 6)
         (clock 1000)
         calls outputs)
     (cl-letf (((symbol-function 'float-time) (lambda (&rest _) clock))
               ((symbol-function 'night/h-mobile-clipboard-ssh-run)
                (lambda (&rest args) (setq calls (append calls (list args)))))
               ((symbol-function 'night/h-mobile-clipboard-osc52-cut)
                (lambda (text) (push text outputs))))
       ,@body)))

(ert-deftest mobile-clipboard-ssh-probes-caches-and-serializes ()
  (mobile-clipboard-test-with-ssh
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "small")
   (should (equal outputs '("small")))
   (should-not calls)
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large first")
   (should (= (length calls) 1))
   (should-not (plist-get (car calls) :text))
   ;; Replace a pending oversized selection before its readiness probe ends.
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large latest")
   (funcall (plist-get (car calls) :callback) t)
   (should (= (length calls) 2))
   (should (equal (plist-get (cadr calls) :text) "large latest"))
   (should (eq (night/h-mobile-clipboard-ssh-ready "phone") 'ready))
   ;; A small selection must not be overwritten by the in-flight large one.
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "new")
   (should (equal outputs '("small")))
   (funcall (plist-get (cadr calls) :callback) t)
   (should (equal outputs '("new" "small")))
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "cached large")
   (should (= (length calls) 3))
   (should (equal (plist-get (nth 2 calls) :text) "cached large"))
   (funcall (plist-get (nth 2 calls) :callback) t)
   (setq clock 1899)
   (should (eq (night/h-mobile-clipboard-ssh-ready "phone") 'ready))
   (setq clock 1900)
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "expired large")
   (should-not (plist-get (nth 3 calls) :text))))

(ert-deftest mobile-clipboard-ssh-failure-expiry-and-reset ()
  (mobile-clipboard-test-with-ssh
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large first")
   (funcall (plist-get (car calls) :callback) nil)
   (should (eq (night/h-mobile-clipboard-ssh-ready "phone") 'down))
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large dropped")
   (should (= (length calls) 1))
   (setq clock 1029)
   (should (eq (night/h-mobile-clipboard-ssh-ready "phone") 'down))
   (setq clock 1030)
   (should-not (night/h-mobile-clipboard-ssh-ready "phone"))
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large retry")
   (funcall (plist-get (nth 1 calls) :callback) t)
   (should (equal (plist-get (nth 2 calls) :text) "large retry"))
   ;; A failed transfer invalidates successful readiness immediately.
   (funcall (plist-get (nth 2 calls) :callback) nil)
   (should (eq (night/h-mobile-clipboard-ssh-ready "phone") 'down))
   (night/h-mobile-clipboard-ssh-cache-put :host "other" :ready t)
   (night/mobile-clipboard-cache-clear "phone")
   (should-not (night/h-mobile-clipboard-ssh-ready "phone"))
   (should (eq (night/h-mobile-clipboard-ssh-ready "other") 'ready))
   (night/mobile-clipboard-cache-clear)
   (should (= (hash-table-count night/h-mobile-clipboard-ssh-cache) 0))))

(ert-deftest mobile-clipboard-tealy-cache-clear-is-scoped ()
  (mobile-clipboard-test-with-ssh
   (night/h-mobile-clipboard-ssh-cache-put :host "tealy" :ready t)
   (night/h-mobile-clipboard-ssh-cache-put :host "other" :ready t)
   (should (commandp #'night/mobile-clipboard-tealy-cache-clear))
   (should (call-interactively #'night/mobile-clipboard-tealy-cache-clear))
   (should-not (night/h-mobile-clipboard-ssh-ready "tealy"))
   (should (eq (night/h-mobile-clipboard-ssh-ready "other") 'ready))
   (should (night/mobile-clipboard-tealy-cache-clear))))

(ert-deftest mobile-clipboard-ssh-failure-releases-new-small-copy ()
  (mobile-clipboard-test-with-ssh
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "large first")
   (night/h-mobile-clipboard-ssh-enqueue :host "phone" :text "new")
   (funcall (plist-get (car calls) :callback) nil)
   (should (equal outputs '("new")))
   (should (= (length calls) 1))))

(ert-deftest mobile-clipboard-ssh-frame-opt-in ()
  (let ((prior (frame-parameter nil 'night/clipboard-ssh-host)) calls)
    (unwind-protect
        (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () t))
                  ((symbol-function 'night/h-mobile-clipboard-ssh-enqueue)
                   (lambda (&rest args) (push args calls)))
                  ((symbol-function 'night/h-mobile-clipboard-osc52-cut)
                   (lambda (_text) (push 'osc calls))))
          (set-frame-parameter nil 'night/clipboard-ssh-host "phone")
          (night/mobile-clipboard-cut "text")
          (should (equal calls '((:host "phone" :text "text"))))
          (set-frame-parameter nil 'night/clipboard-ssh-host nil)
          (night/mobile-clipboard-cut "text")
          (should (eq (car calls) 'osc)))
      (set-frame-parameter nil 'night/clipboard-ssh-host prior))))

(ert-deftest mobile-clipboard-ssh-runner-utf8-and-timeout ()
  (let ((real-make-process (symbol-function 'make-process))
        (night/mobile-clipboard-ssh-timeout 2)
        command captured process results)
    ;; Exercise real pipe encoding, EOF, and sentinel behavior without a phone.
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq command (plist-get args :command))
                 (setq args (plist-put args :command '("/bin/cat")))
                 (setq args (plist-put args :filter
                                       (lambda (_proc text)
                                         (setq captured (concat captured text)))))
                 (setq process (apply real-make-process args)))))
      (night/h-mobile-clipboard-ssh-run
       :host "phone" :text "hello فارسی 🦊\n\n"
       :callback (lambda (ok) (push ok results)))
      (let ((deadline (+ (float-time) 3)))
        (while (and (not results) (< (float-time) deadline))
          (accept-process-output nil 0.01)))
      (should (equal results '(t)))
      (should (equal captured "hello فارسی 🦊\n\n"))
      (should (equal (last command 3) '("--" "phone" "termux-clipboard-set")))
      (should-not (member "hello فارسی 🦊\n\n" command)))
    (setq results nil night/mobile-clipboard-ssh-timeout 0.03)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq process (apply real-make-process
                                      (plist-put args :command '("/bin/sleep" "2")))))))
      (night/h-mobile-clipboard-ssh-run
       :host "phone" :callback (lambda (ok) (push ok results)))
      (let ((deadline (+ (float-time) 1)))
        (while (and (not results) (< (float-time) deadline))
          (accept-process-output nil 0.01)))
      (accept-process-output nil 0.05)
      (should (equal results '(nil)))
      (should-not (process-live-p process)))))

(ert-deftest mobile-clipboard-ssh-get-utf8-newlines-and-stderr-isolation ()
  (let ((real-make-process (symbol-function 'make-process)) command)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq command (plist-get args :command))
                 (apply real-make-process
                        (plist-put args :command
                                   '("/bin/sh" "-c"
                                     "printf 'hello فارسی 🦊\\n\\n'; printf noise >&2"))))))
      (should (equal (night/h-mobile-clipboard-ssh-get "phone")
                     "hello فارسی 🦊\n\n"))
      (should (equal (last command 3)
                     '("--" "phone" "termux-clipboard-get"))))))

(ert-deftest mobile-clipboard-ssh-get-failure-timeout-and-cleanup ()
  (let ((real-make-process (symbol-function 'make-process))
        (night/mobile-clipboard-ssh-timeout 0.03)
        seen-buffers process)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq seen-buffers
                       (list (plist-get args :buffer) (plist-get args :stderr)))
                 (setq process
                       (apply real-make-process
                              (plist-put args :command '("/bin/sleep" "2")))))))
      (should-error (night/h-mobile-clipboard-ssh-get "phone") :type 'user-error)
      (should-not (process-live-p process))
      (should-not (cl-some #'buffer-live-p seen-buffers)))
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq seen-buffers
                       (list (plist-get args :buffer) (plist-get args :stderr)))
                 (apply real-make-process
                        (plist-put args :command '("/usr/bin/false"))))))
      (should-error (night/h-mobile-clipboard-ssh-get "phone") :type 'user-error)
      (should-not (cl-some #'buffer-live-p seen-buffers)))))

(ert-deftest mobile-clipboard-current-kill-routing-repeat-rotation-and-empty ()
  (let ((kill-ring '("old" "older"))
        (kill-ring-yank-pointer nil)
        (values '("remote" "remote" "remote" ""))
        (mobile t)
        calls)
    (setq kill-ring-yank-pointer kill-ring)
    (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () mobile))
              ((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (and (eq parameter 'night/clipboard-ssh-host) "phone")))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (host &optional _command) (push host calls) (pop values))))
      (should (equal (current-kill 0) "remote"))
      (should (equal (current-kill 0) "remote"))
      (should (= (cl-count "remote" kill-ring :test #'equal) 1))
      (should (equal (current-kill 1) "old"))
      ;; Rotation does not fetch; a subsequent normal paste freshly reads and
      ;; resets the yank pointer even when the clipboard text is unchanged.
      (should (= (length calls) 2))
      (should (equal (current-kill 0) "remote"))
      (should (equal (car kill-ring-yank-pointer) "remote"))
      ;; A genuinely empty clipboard must not return the previous kill.
      (should (equal (current-kill 0) ""))
      (should (equal (car kill-ring) ""))
      (setq mobile nil)
      (should (equal (current-kill 0) ""))
      (should (= (length calls) 4)))))

(ert-deftest mobile-clipboard-current-kill-import-bypasses-copy-policy ()
  (let ((kill-ring '("stale"))
        (kill-ring-yank-pointer nil)
        cut-events)
    (setq kill-ring-yank-pointer kill-ring)
    (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () t))
              ((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (and (eq parameter 'night/clipboard-ssh-host) "phone")))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (_host &optional _command) " \n\n"))
              ((symbol-function 'night/mobile-clipboard-cut)
               (lambda (text) (push text cut-events))))
      (unwind-protect
          (progn
            (advice-add 'kill-new :around #'night/h-kill-skip-whitespace)
            (should (equal (current-kill 0) " \n\n"))
            (should (equal (car kill-ring) " \n\n"))
            (should-not cut-events))
        (advice-remove 'kill-new #'night/h-kill-skip-whitespace)))))

(ert-deftest mobile-clipboard-ssh-get-waits-for-queued-copy ()
  (let ((night/h-mobile-clipboard-ssh-jobs (make-hash-table :test #'equal))
        (real-make-process (symbol-function 'make-process))
        (real-accept-process-output (symbol-function 'accept-process-output))
        waited)
    (puthash "phone" (list :busy t :pending nil)
             night/h-mobile-clipboard-ssh-jobs)
    (cl-letf (((symbol-function 'accept-process-output)
              (lambda (&rest _)
                 (cond
                  ((not waited)
                   (setq waited t)
                   (setf (plist-get
                          (gethash "phone" night/h-mobile-clipboard-ssh-jobs)
                          :busy) nil))
                  (t (funcall real-accept-process-output nil 0.01)))))
              ((symbol-function 'make-process)
               (lambda (&rest args)
                 (apply real-make-process
                        (plist-put args :command
                                   '("/bin/sh" "-c" "printf ready"))))))
      (should (equal (night/h-mobile-clipboard-ssh-get "phone") "ready"))
      (should waited))))

(ert-deftest mobile-clipboard-ssh-get-quit-cleans-process-and-buffers ()
  (let ((real-make-process (symbol-function 'make-process))
        seen-buffers process)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq seen-buffers
                       (list (plist-get args :buffer) (plist-get args :stderr)))
                 (setq process
                       (apply real-make-process
                              (plist-put args :command '("/bin/sleep" "2"))))))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _) (signal 'quit nil))))
      (should (condition-case nil
                  (progn (night/h-mobile-clipboard-ssh-get "phone") nil)
                (quit t)))
      (should-not (process-live-p process))
      (should-not (cl-some #'buffer-live-p seen-buffers)))))

(ert-deftest mobile-clipboard-evil-paste-pop-inhibits-fresh-read ()
  (let ((kill-ring '("new" "old"))
        (kill-ring-yank-pointer nil)
        calls)
    (setq kill-ring-yank-pointer kill-ring)
    (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () t))
              ((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (and (eq parameter 'night/clipboard-ssh-host) "phone")))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (_host &optional _command) (push t calls) "remote")))
      (should
       (equal (night/h-mobile-clipboard-evil-paste-pop
               (lambda ()
                 ;; Evil first rotates, then its paste implementation asks for
                 ;; index zero from a temporary one-element kill ring.
                 (let* ((rotated (current-kill 1))
                        (kill-ring (list rotated))
                        (kill-ring-yank-pointer kill-ring))
                   (current-kill 0))))
              "old"))
      (should-not calls))))

(ert-deftest mobile-clipboard-xterm-paste-keeps-terminal-text ()
  (let ((kill-ring '("stale"))
        (kill-ring-yank-pointer nil))
    (setq kill-ring-yank-pointer kill-ring)
    (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () t))
              ((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (and (eq parameter 'night/clipboard-ssh-host) "phone")))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (_host &optional _command)
                 (ert-fail "SSH getter must not run"))))
      (with-temp-buffer
        (xterm-paste '(xterm-paste "terminal paste"))
        (should (equal (buffer-string) "terminal paste"))))))

(ert-deftest mobile-clipboard-ssh-paste-toggle-and-routing-gates ()
  (let ((night/ssh-paste-enabled-p t)
        (kill-ring '("local"))
        (kill-ring-yank-pointer nil)
        mobile host calls)
    (setq kill-ring-yank-pointer kill-ring)
    (cl-letf (((symbol-function 'night/mobile-clipboard-frame-p) (lambda () mobile))
              ((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (and (eq parameter 'night/clipboard-ssh-host) host)))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (&rest _) (push t calls) "remote")))
      (setq mobile t host "phone")
      (should (equal (current-kill 0) "remote"))
      (night/ssh-paste-toggle -1)
      (should-not night/ssh-paste-enabled-p)
      (should (equal (current-kill 0) "remote"))
      (should (= (length calls) 1))
      (night/ssh-paste-toggle 1)
      (setq mobile nil)
      (should (equal (current-kill 0) "remote"))
      (should (= (length calls) 1))
      (setq mobile t host "bad host")
      (should-error (current-kill 0) :type 'user-error)
      (setq host nil)
      (should (equal (current-kill 0) "remote")))))

(ert-deftest mobile-clipboard-explicit-paste-commands ()
  (let ((night/ssh-paste-enabled-p nil)
        host command calls)
    (cl-letf (((symbol-function 'frame-parameter)
               (lambda (_frame parameter)
                 (cond ((eq parameter 'night/clipboard-ssh-host) host)
                       ((eq parameter 'night/clipboard-ssh-paste-command) command))))
              ((symbol-function 'night/h-mobile-clipboard-ssh-get)
               (lambda (&rest args) (push args calls) "text")))
      (with-temp-buffer
        (setq host "phone")
        (night/ssh-paste)
        (should (equal (buffer-string) "text"))
        (should (equal (car calls) '("phone" nil)))
        (erase-buffer)
        (setq command "custom trusted getter")
        (night/ssh-paste)
        (should (equal (car calls) '("phone" "custom trusted getter")))
        (erase-buffer)
        (night/tealy-paste)
        (should (equal (buffer-string) "text"))
        (should (equal (car calls) '("tealy" "termux-clipboard-get")))
        (setq host nil)
        (should-error (night/ssh-paste) :type 'user-error)))))

(ert-run-tests-batch-and-exit)
