;;; autoload/org/night-babel-tests.el -*- lexical-binding: t; -*-

(defun night/babel-tests ()
  (interactive)
  (copy-to-buffer "*my-test*" (point-min) (point-max))
  (org-babel-execute-buffer)
  (night/diff-buffers "*my-test*" (current-buffer))
  ;; (diff-buffers "*my-test*" (current-buffer) (list "--unified=30"))
  )
(defun night/babel-tests-tmp ()
  (interactive)
  (let ((contents (buffer-string))
    (buf (current-buffer)))
    (with-current-buffer (get-buffer-create "*my-test*")
      (erase-buffer)
      (insert contents)
      (org-mode)
      (org-babel-execute-buffer)
      (ediff-buffers buf "*my-test*"))))
